/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MailAPdfRouteImport } from './routes/mail-a-pdf'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RespondToAGovernmentNoticeRouteImport } from './routes/respond-to-a-government-notice'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsAgencyActionRouteImport } from './routes/workflows/agency-action'
import { Route as WorkflowsAnalyzeRouteImport } from './routes/workflows/analyze'
import { Route as WorkflowsBenefitsNoticeRouteImport } from './routes/workflows/benefits-notice'
import { Route as WorkflowsClaimProofPackageRouteImport } from './routes/workflows/claim-proof-package'
import { Route as WorkflowsCodeEnforcementRouteImport } from './routes/workflows/code-enforcement'
import { Route as WorkflowsCourtSummonsRouteImport } from './routes/workflows/court-summons'
import { Route as WorkflowsCp14ResponseRouteImport } from './routes/workflows/cp14-response'
import { Route as WorkflowsCp2000ResponseRouteImport } from './routes/workflows/cp2000-response'
import { Route as WorkflowsCp504ResponseRouteImport } from './routes/workflows/cp504-response'
import { Route as WorkflowsCp523ResponseRouteImport } from './routes/workflows/cp523-response'
import { Route as WorkflowsDmvNoticeRouteImport } from './routes/workflows/dmv-notice'
import { Route as WorkflowsEquifaxDisputeRouteImport } from './routes/workflows/equifax-dispute'
import { Route as WorkflowsExperianDisputeRouteImport } from './routes/workflows/experian-dispute'
import { Route as WorkflowsFileAppealRouteImport } from './routes/workflows/file-appeal'
import { Route as WorkflowsIrsNoticeRouteImport } from './routes/workflows/irs-notice'
import { Route as WorkflowsPermitCorrectionRouteImport } from './routes/workflows/permit-correction'
import { Route as WorkflowsPermitDenialResponseRouteImport } from './routes/workflows/permit-denial-response'
import { Route as WorkflowsRespondToABenefitsNoticeRouteImport } from './routes/workflows/respond-to-a-benefits-notice'
import { Route as WorkflowsRespondToACourtSummonsRouteImport } from './routes/workflows/respond-to-a-court-summons'
import { Route as WorkflowsRespondToADmvNoticeRouteImport } from './routes/workflows/respond-to-a-dmv-notice'
import { Route as WorkflowsRespondToAPermitCorrectionNoticeRouteImport } from './routes/workflows/respond-to-a-permit-correction-notice'
import { Route as WorkflowsRespondToATaxNoticeRouteImport } from './routes/workflows/respond-to-a-tax-notice'
import { Route as WorkflowsRespondToAUscisNoticeRouteImport } from './routes/workflows/respond-to-a-uscis-notice'
import { Route as WorkflowsRespondToAnAgencyActionRouteImport } from './routes/workflows/respond-to-an-agency-action'
import { Route as WorkflowsRespondToAnIrsNoticeRouteImport } from './routes/workflows/respond-to-an-irs-notice'
import { Route as WorkflowsRespondToAnSsaNoticeRouteImport } from './routes/workflows/respond-to-an-ssa-notice'
import { Route as WorkflowsRespondToCodeEnforcementNoticeRouteImport } from './routes/workflows/respond-to-code-enforcement-notice'
import { Route as WorkflowsRespondToCp14NoticeRouteImport } from './routes/workflows/respond-to-cp14-notice'
import { Route as WorkflowsRespondToCp2000NoticeRouteImport } from './routes/workflows/respond-to-cp2000-notice'
import { Route as WorkflowsSsaNoticeRouteImport } from './routes/workflows/ssa-notice'
import { Route as WorkflowsTaxNoticeRouteImport } from './routes/workflows/tax-notice'
import { Route as WorkflowsTenantEvictionResponseRouteImport } from './routes/workflows/tenant-eviction-response'
import { Route as WorkflowsTenantRepairDemandRouteImport } from './routes/workflows/tenant-repair-demand'
import { Route as WorkflowsTransunionDisputeRouteImport } from './routes/workflows/transunion-dispute'
import { Route as WorkflowsUscisNoticeRouteImport } from './routes/workflows/uscis-notice'
import { Route as ApiAdminHealthRouteImport } from './routes/api/admin/health'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiCasesIndexRouteImport } from './routes/api/cases/index'
import { Route as ApiCasesCaseIdRouteImport } from './routes/api/cases/$caseId'
import { Route as ApiCasesCreateRouteImport } from './routes/api/cases/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAPdfRoute = MailAPdfRouteImport.update({
  id: '/mail-a-pdf',
  path: '/mail-a-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondToAGovernmentNoticeRoute =
  RespondToAGovernmentNoticeRouteImport.update({
    id: '/respond-to-a-government-notice',
    path: '/respond-to-a-government-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsAgencyActionRoute = WorkflowsAgencyActionRouteImport.update({
  id: '/workflows/agency-action',
  path: '/workflows/agency-action',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsAnalyzeRoute = WorkflowsAnalyzeRouteImport.update({
  id: '/workflows/analyze',
  path: '/workflows/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsBenefitsNoticeRoute = WorkflowsBenefitsNoticeRouteImport.update({
  id: '/workflows/benefits-notice',
  path: '/workflows/benefits-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsClaimProofPackageRoute =
  WorkflowsClaimProofPackageRouteImport.update({
    id: '/workflows/claim-proof-package',
    path: '/workflows/claim-proof-package',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsCodeEnforcementRoute =
  WorkflowsCodeEnforcementRouteImport.update({
    id: '/workflows/code-enforcement',
    path: '/workflows/code-enforcement',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsCourtSummonsRoute = WorkflowsCourtSummonsRouteImport.update({
  id: '/workflows/court-summons',
  path: '/workflows/court-summons',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp14ResponseRoute = WorkflowsCp14ResponseRouteImport.update({
  id: '/workflows/cp14-response',
  path: '/workflows/cp14-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp2000ResponseRoute = WorkflowsCp2000ResponseRouteImport.update({
  id: '/workflows/cp2000-response',
  path: '/workflows/cp2000-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp504ResponseRoute = WorkflowsCp504ResponseRouteImport.update({
  id: '/workflows/cp504-response',
  path: '/workflows/cp504-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCp523ResponseRoute = WorkflowsCp523ResponseRouteImport.update({
  id: '/workflows/cp523-response',
  path: '/workflows/cp523-response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsDmvNoticeRoute = WorkflowsDmvNoticeRouteImport.update({
  id: '/workflows/dmv-notice',
  path: '/workflows/dmv-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsEquifaxDisputeRoute = WorkflowsEquifaxDisputeRouteImport.update({
  id: '/workflows/equifax-dispute',
  path: '/workflows/equifax-dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExperianDisputeRoute =
  WorkflowsExperianDisputeRouteImport.update({
    id: '/workflows/experian-dispute',
    path: '/workflows/experian-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsFileAppealRoute = WorkflowsFileAppealRouteImport.update({
  id: '/workflows/file-appeal',
  path: '/workflows/file-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIrsNoticeRoute = WorkflowsIrsNoticeRouteImport.update({
  id: '/workflows/irs-notice',
  path: '/workflows/irs-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsPermitCorrectionRoute =
  WorkflowsPermitCorrectionRouteImport.update({
    id: '/workflows/permit-correction',
    path: '/workflows/permit-correction',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsPermitDenialResponseRoute =
  WorkflowsPermitDenialResponseRouteImport.update({
    id: '/workflows/permit-denial-response',
    path: '/workflows/permit-denial-response',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToABenefitsNoticeRoute =
  WorkflowsRespondToABenefitsNoticeRouteImport.update({
    id: '/workflows/respond-to-a-benefits-notice',
    path: '/workflows/respond-to-a-benefits-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToACourtSummonsRoute =
  WorkflowsRespondToACourtSummonsRouteImport.update({
    id: '/workflows/respond-to-a-court-summons',
    path: '/workflows/respond-to-a-court-summons',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToADmvNoticeRoute =
  WorkflowsRespondToADmvNoticeRouteImport.update({
    id: '/workflows/respond-to-a-dmv-notice',
    path: '/workflows/respond-to-a-dmv-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAPermitCorrectionNoticeRoute =
  WorkflowsRespondToAPermitCorrectionNoticeRouteImport.update({
    id: '/workflows/respond-to-a-permit-correction-notice',
    path: '/workflows/respond-to-a-permit-correction-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToATaxNoticeRoute =
  WorkflowsRespondToATaxNoticeRouteImport.update({
    id: '/workflows/respond-to-a-tax-notice',
    path: '/workflows/respond-to-a-tax-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAUscisNoticeRoute =
  WorkflowsRespondToAUscisNoticeRouteImport.update({
    id: '/workflows/respond-to-a-uscis-notice',
    path: '/workflows/respond-to-a-uscis-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnAgencyActionRoute =
  WorkflowsRespondToAnAgencyActionRouteImport.update({
    id: '/workflows/respond-to-an-agency-action',
    path: '/workflows/respond-to-an-agency-action',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnIrsNoticeRoute =
  WorkflowsRespondToAnIrsNoticeRouteImport.update({
    id: '/workflows/respond-to-an-irs-notice',
    path: '/workflows/respond-to-an-irs-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToAnSsaNoticeRoute =
  WorkflowsRespondToAnSsaNoticeRouteImport.update({
    id: '/workflows/respond-to-an-ssa-notice',
    path: '/workflows/respond-to-an-ssa-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCodeEnforcementNoticeRoute =
  WorkflowsRespondToCodeEnforcementNoticeRouteImport.update({
    id: '/workflows/respond-to-code-enforcement-notice',
    path: '/workflows/respond-to-code-enforcement-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCp14NoticeRoute =
  WorkflowsRespondToCp14NoticeRouteImport.update({
    id: '/workflows/respond-to-cp14-notice',
    path: '/workflows/respond-to-cp14-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToCp2000NoticeRoute =
  WorkflowsRespondToCp2000NoticeRouteImport.update({
    id: '/workflows/respond-to-cp2000-notice',
    path: '/workflows/respond-to-cp2000-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsSsaNoticeRoute = WorkflowsSsaNoticeRouteImport.update({
  id: '/workflows/ssa-notice',
  path: '/workflows/ssa-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsTaxNoticeRoute = WorkflowsTaxNoticeRouteImport.update({
  id: '/workflows/tax-notice',
  path: '/workflows/tax-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsTenantEvictionResponseRoute =
  WorkflowsTenantEvictionResponseRouteImport.update({
    id: '/workflows/tenant-eviction-response',
    path: '/workflows/tenant-eviction-response',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsTenantRepairDemandRoute =
  WorkflowsTenantRepairDemandRouteImport.update({
    id: '/workflows/tenant-repair-demand',
    path: '/workflows/tenant-repair-demand',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsTransunionDisputeRoute =
  WorkflowsTransunionDisputeRouteImport.update({
    id: '/workflows/transunion-dispute',
    path: '/workflows/transunion-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsUscisNoticeRoute = WorkflowsUscisNoticeRouteImport.update({
  id: '/workflows/uscis-notice',
  path: '/workflows/uscis-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHealthRoute = ApiAdminHealthRouteImport.update({
  id: '/api/admin/health',
  path: '/api/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesIndexRoute = ApiCasesIndexRouteImport.update({
  id: '/api/cases/',
  path: '/api/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCaseIdRoute = ApiCasesCaseIdRouteImport.update({
  id: '/api/cases/$caseId',
  path: '/api/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCreateRoute = ApiCasesCreateRouteImport.update({
  id: '/api/cases/create',
  path: '/api/cases/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/benefits-notice': typeof WorkflowsBenefitsNoticeRoute
  '/workflows/claim-proof-package': typeof WorkflowsClaimProofPackageRoute
  '/workflows/code-enforcement': typeof WorkflowsCodeEnforcementRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/cp523-response': typeof WorkflowsCp523ResponseRoute
  '/workflows/dmv-notice': typeof WorkflowsDmvNoticeRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/permit-correction': typeof WorkflowsPermitCorrectionRoute
  '/workflows/permit-denial-response': typeof WorkflowsPermitDenialResponseRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/ssa-notice': typeof WorkflowsSsaNoticeRoute
  '/workflows/tax-notice': typeof WorkflowsTaxNoticeRoute
  '/workflows/tenant-eviction-response': typeof WorkflowsTenantEvictionResponseRoute
  '/workflows/tenant-repair-demand': typeof WorkflowsTenantRepairDemandRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/workflows/uscis-notice': typeof WorkflowsUscisNoticeRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRoute
  '/api/cases/create': typeof ApiCasesCreateRoute
  '/api/cases/': typeof ApiCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/benefits-notice': typeof WorkflowsBenefitsNoticeRoute
  '/workflows/claim-proof-package': typeof WorkflowsClaimProofPackageRoute
  '/workflows/code-enforcement': typeof WorkflowsCodeEnforcementRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/cp523-response': typeof WorkflowsCp523ResponseRoute
  '/workflows/dmv-notice': typeof WorkflowsDmvNoticeRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/permit-correction': typeof WorkflowsPermitCorrectionRoute
  '/workflows/permit-denial-response': typeof WorkflowsPermitDenialResponseRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/ssa-notice': typeof WorkflowsSsaNoticeRoute
  '/workflows/tax-notice': typeof WorkflowsTaxNoticeRoute
  '/workflows/tenant-eviction-response': typeof WorkflowsTenantEvictionResponseRoute
  '/workflows/tenant-repair-demand': typeof WorkflowsTenantRepairDemandRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/workflows/uscis-notice': typeof WorkflowsUscisNoticeRoute
  '/resources': typeof ResourcesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRoute
  '/api/cases/create': typeof ApiCasesCreateRoute
  '/api/cases': typeof ApiCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/respond-to-a-government-notice': typeof RespondToAGovernmentNoticeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/agency-action': typeof WorkflowsAgencyActionRoute
  '/workflows/analyze': typeof WorkflowsAnalyzeRoute
  '/workflows/benefits-notice': typeof WorkflowsBenefitsNoticeRoute
  '/workflows/claim-proof-package': typeof WorkflowsClaimProofPackageRoute
  '/workflows/code-enforcement': typeof WorkflowsCodeEnforcementRoute
  '/workflows/court-summons': typeof WorkflowsCourtSummonsRoute
  '/workflows/cp14-response': typeof WorkflowsCp14ResponseRoute
  '/workflows/cp2000-response': typeof WorkflowsCp2000ResponseRoute
  '/workflows/cp504-response': typeof WorkflowsCp504ResponseRoute
  '/workflows/cp523-response': typeof WorkflowsCp523ResponseRoute
  '/workflows/dmv-notice': typeof WorkflowsDmvNoticeRoute
  '/workflows/equifax-dispute': typeof WorkflowsEquifaxDisputeRoute
  '/workflows/experian-dispute': typeof WorkflowsExperianDisputeRoute
  '/workflows/file-appeal': typeof WorkflowsFileAppealRoute
  '/workflows/irs-notice': typeof WorkflowsIrsNoticeRoute
  '/workflows/permit-correction': typeof WorkflowsPermitCorrectionRoute
  '/workflows/permit-denial-response': typeof WorkflowsPermitDenialResponseRoute
  '/workflows/respond-to-a-benefits-notice': typeof WorkflowsRespondToABenefitsNoticeRoute
  '/workflows/respond-to-a-court-summons': typeof WorkflowsRespondToACourtSummonsRoute
  '/workflows/respond-to-a-dmv-notice': typeof WorkflowsRespondToADmvNoticeRoute
  '/workflows/respond-to-a-permit-correction-notice': typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  '/workflows/respond-to-a-tax-notice': typeof WorkflowsRespondToATaxNoticeRoute
  '/workflows/respond-to-a-uscis-notice': typeof WorkflowsRespondToAUscisNoticeRoute
  '/workflows/respond-to-an-agency-action': typeof WorkflowsRespondToAnAgencyActionRoute
  '/workflows/respond-to-an-irs-notice': typeof WorkflowsRespondToAnIrsNoticeRoute
  '/workflows/respond-to-an-ssa-notice': typeof WorkflowsRespondToAnSsaNoticeRoute
  '/workflows/respond-to-code-enforcement-notice': typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  '/workflows/respond-to-cp14-notice': typeof WorkflowsRespondToCp14NoticeRoute
  '/workflows/respond-to-cp2000-notice': typeof WorkflowsRespondToCp2000NoticeRoute
  '/workflows/ssa-notice': typeof WorkflowsSsaNoticeRoute
  '/workflows/tax-notice': typeof WorkflowsTaxNoticeRoute
  '/workflows/tenant-eviction-response': typeof WorkflowsTenantEvictionResponseRoute
  '/workflows/tenant-repair-demand': typeof WorkflowsTenantRepairDemandRoute
  '/workflows/transunion-dispute': typeof WorkflowsTransunionDisputeRoute
  '/workflows/uscis-notice': typeof WorkflowsUscisNoticeRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdRoute
  '/api/cases/create': typeof ApiCasesCreateRoute
  '/api/cases/': typeof ApiCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-government-notice'
    | '/start'
    | '/terms'
    | '/api/documents'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/benefits-notice'
    | '/workflows/claim-proof-package'
    | '/workflows/code-enforcement'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/cp523-response'
    | '/workflows/dmv-notice'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/permit-correction'
    | '/workflows/permit-denial-response'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/ssa-notice'
    | '/workflows/tax-notice'
    | '/workflows/tenant-eviction-response'
    | '/workflows/tenant-repair-demand'
    | '/workflows/transunion-dispute'
    | '/workflows/uscis-notice'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/cases/$caseId'
    | '/api/cases/create'
    | '/api/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-government-notice'
    | '/start'
    | '/terms'
    | '/api/documents'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/benefits-notice'
    | '/workflows/claim-proof-package'
    | '/workflows/code-enforcement'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/cp523-response'
    | '/workflows/dmv-notice'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/permit-correction'
    | '/workflows/permit-denial-response'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/ssa-notice'
    | '/workflows/tax-notice'
    | '/workflows/tenant-eviction-response'
    | '/workflows/tenant-repair-demand'
    | '/workflows/transunion-dispute'
    | '/workflows/uscis-notice'
    | '/resources'
    | '/workflows'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/cases/$caseId'
    | '/api/cases/create'
    | '/api/cases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/respond-to-a-government-notice'
    | '/start'
    | '/terms'
    | '/api/documents'
    | '/resources/$slug'
    | '/workflows/agency-action'
    | '/workflows/analyze'
    | '/workflows/benefits-notice'
    | '/workflows/claim-proof-package'
    | '/workflows/code-enforcement'
    | '/workflows/court-summons'
    | '/workflows/cp14-response'
    | '/workflows/cp2000-response'
    | '/workflows/cp504-response'
    | '/workflows/cp523-response'
    | '/workflows/dmv-notice'
    | '/workflows/equifax-dispute'
    | '/workflows/experian-dispute'
    | '/workflows/file-appeal'
    | '/workflows/irs-notice'
    | '/workflows/permit-correction'
    | '/workflows/permit-denial-response'
    | '/workflows/respond-to-a-benefits-notice'
    | '/workflows/respond-to-a-court-summons'
    | '/workflows/respond-to-a-dmv-notice'
    | '/workflows/respond-to-a-permit-correction-notice'
    | '/workflows/respond-to-a-tax-notice'
    | '/workflows/respond-to-a-uscis-notice'
    | '/workflows/respond-to-an-agency-action'
    | '/workflows/respond-to-an-irs-notice'
    | '/workflows/respond-to-an-ssa-notice'
    | '/workflows/respond-to-code-enforcement-notice'
    | '/workflows/respond-to-cp14-notice'
    | '/workflows/respond-to-cp2000-notice'
    | '/workflows/ssa-notice'
    | '/workflows/tax-notice'
    | '/workflows/tenant-eviction-response'
    | '/workflows/tenant-repair-demand'
    | '/workflows/transunion-dispute'
    | '/workflows/uscis-notice'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/cases/$caseId'
    | '/api/cases/create'
    | '/api/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MailAPdfRoute: typeof MailAPdfRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RespondToAGovernmentNoticeRoute: typeof RespondToAGovernmentNoticeRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  WorkflowsAgencyActionRoute: typeof WorkflowsAgencyActionRoute
  WorkflowsAnalyzeRoute: typeof WorkflowsAnalyzeRoute
  WorkflowsBenefitsNoticeRoute: typeof WorkflowsBenefitsNoticeRoute
  WorkflowsClaimProofPackageRoute: typeof WorkflowsClaimProofPackageRoute
  WorkflowsCodeEnforcementRoute: typeof WorkflowsCodeEnforcementRoute
  WorkflowsCourtSummonsRoute: typeof WorkflowsCourtSummonsRoute
  WorkflowsCp14ResponseRoute: typeof WorkflowsCp14ResponseRoute
  WorkflowsCp2000ResponseRoute: typeof WorkflowsCp2000ResponseRoute
  WorkflowsCp504ResponseRoute: typeof WorkflowsCp504ResponseRoute
  WorkflowsCp523ResponseRoute: typeof WorkflowsCp523ResponseRoute
  WorkflowsDmvNoticeRoute: typeof WorkflowsDmvNoticeRoute
  WorkflowsEquifaxDisputeRoute: typeof WorkflowsEquifaxDisputeRoute
  WorkflowsExperianDisputeRoute: typeof WorkflowsExperianDisputeRoute
  WorkflowsFileAppealRoute: typeof WorkflowsFileAppealRoute
  WorkflowsIrsNoticeRoute: typeof WorkflowsIrsNoticeRoute
  WorkflowsPermitCorrectionRoute: typeof WorkflowsPermitCorrectionRoute
  WorkflowsPermitDenialResponseRoute: typeof WorkflowsPermitDenialResponseRoute
  WorkflowsRespondToABenefitsNoticeRoute: typeof WorkflowsRespondToABenefitsNoticeRoute
  WorkflowsRespondToACourtSummonsRoute: typeof WorkflowsRespondToACourtSummonsRoute
  WorkflowsRespondToADmvNoticeRoute: typeof WorkflowsRespondToADmvNoticeRoute
  WorkflowsRespondToAPermitCorrectionNoticeRoute: typeof WorkflowsRespondToAPermitCorrectionNoticeRoute
  WorkflowsRespondToATaxNoticeRoute: typeof WorkflowsRespondToATaxNoticeRoute
  WorkflowsRespondToAUscisNoticeRoute: typeof WorkflowsRespondToAUscisNoticeRoute
  WorkflowsRespondToAnAgencyActionRoute: typeof WorkflowsRespondToAnAgencyActionRoute
  WorkflowsRespondToAnIrsNoticeRoute: typeof WorkflowsRespondToAnIrsNoticeRoute
  WorkflowsRespondToAnSsaNoticeRoute: typeof WorkflowsRespondToAnSsaNoticeRoute
  WorkflowsRespondToCodeEnforcementNoticeRoute: typeof WorkflowsRespondToCodeEnforcementNoticeRoute
  WorkflowsRespondToCp14NoticeRoute: typeof WorkflowsRespondToCp14NoticeRoute
  WorkflowsRespondToCp2000NoticeRoute: typeof WorkflowsRespondToCp2000NoticeRoute
  WorkflowsSsaNoticeRoute: typeof WorkflowsSsaNoticeRoute
  WorkflowsTaxNoticeRoute: typeof WorkflowsTaxNoticeRoute
  WorkflowsTenantEvictionResponseRoute: typeof WorkflowsTenantEvictionResponseRoute
  WorkflowsTenantRepairDemandRoute: typeof WorkflowsTenantRepairDemandRoute
  WorkflowsTransunionDisputeRoute: typeof WorkflowsTransunionDisputeRoute
  WorkflowsUscisNoticeRoute: typeof WorkflowsUscisNoticeRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiAdminHealthRoute: typeof ApiAdminHealthRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiCasesCaseIdRoute: typeof ApiCasesCaseIdRoute
  ApiCasesCreateRoute: typeof ApiCasesCreateRoute
  ApiCasesIndexRoute: typeof ApiCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-pdf': {
      id: '/mail-a-pdf'
      path: '/mail-a-pdf'
      fullPath: '/mail-a-pdf'
      preLoaderRoute: typeof MailAPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respond-to-a-government-notice': {
      id: '/respond-to-a-government-notice'
      path: '/respond-to-a-government-notice'
      fullPath: '/respond-to-a-government-notice'
      preLoaderRoute: typeof RespondToAGovernmentNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/agency-action': {
      id: '/workflows/agency-action'
      path: '/workflows/agency-action'
      fullPath: '/workflows/agency-action'
      preLoaderRoute: typeof WorkflowsAgencyActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/analyze': {
      id: '/workflows/analyze'
      path: '/workflows/analyze'
      fullPath: '/workflows/analyze'
      preLoaderRoute: typeof WorkflowsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/benefits-notice': {
      id: '/workflows/benefits-notice'
      path: '/workflows/benefits-notice'
      fullPath: '/workflows/benefits-notice'
      preLoaderRoute: typeof WorkflowsBenefitsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/claim-proof-package': {
      id: '/workflows/claim-proof-package'
      path: '/workflows/claim-proof-package'
      fullPath: '/workflows/claim-proof-package'
      preLoaderRoute: typeof WorkflowsClaimProofPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/code-enforcement': {
      id: '/workflows/code-enforcement'
      path: '/workflows/code-enforcement'
      fullPath: '/workflows/code-enforcement'
      preLoaderRoute: typeof WorkflowsCodeEnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/court-summons': {
      id: '/workflows/court-summons'
      path: '/workflows/court-summons'
      fullPath: '/workflows/court-summons'
      preLoaderRoute: typeof WorkflowsCourtSummonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp14-response': {
      id: '/workflows/cp14-response'
      path: '/workflows/cp14-response'
      fullPath: '/workflows/cp14-response'
      preLoaderRoute: typeof WorkflowsCp14ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp2000-response': {
      id: '/workflows/cp2000-response'
      path: '/workflows/cp2000-response'
      fullPath: '/workflows/cp2000-response'
      preLoaderRoute: typeof WorkflowsCp2000ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp504-response': {
      id: '/workflows/cp504-response'
      path: '/workflows/cp504-response'
      fullPath: '/workflows/cp504-response'
      preLoaderRoute: typeof WorkflowsCp504ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/cp523-response': {
      id: '/workflows/cp523-response'
      path: '/workflows/cp523-response'
      fullPath: '/workflows/cp523-response'
      preLoaderRoute: typeof WorkflowsCp523ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/dmv-notice': {
      id: '/workflows/dmv-notice'
      path: '/workflows/dmv-notice'
      fullPath: '/workflows/dmv-notice'
      preLoaderRoute: typeof WorkflowsDmvNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/equifax-dispute': {
      id: '/workflows/equifax-dispute'
      path: '/workflows/equifax-dispute'
      fullPath: '/workflows/equifax-dispute'
      preLoaderRoute: typeof WorkflowsEquifaxDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/experian-dispute': {
      id: '/workflows/experian-dispute'
      path: '/workflows/experian-dispute'
      fullPath: '/workflows/experian-dispute'
      preLoaderRoute: typeof WorkflowsExperianDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/file-appeal': {
      id: '/workflows/file-appeal'
      path: '/workflows/file-appeal'
      fullPath: '/workflows/file-appeal'
      preLoaderRoute: typeof WorkflowsFileAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/irs-notice': {
      id: '/workflows/irs-notice'
      path: '/workflows/irs-notice'
      fullPath: '/workflows/irs-notice'
      preLoaderRoute: typeof WorkflowsIrsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/permit-correction': {
      id: '/workflows/permit-correction'
      path: '/workflows/permit-correction'
      fullPath: '/workflows/permit-correction'
      preLoaderRoute: typeof WorkflowsPermitCorrectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/permit-denial-response': {
      id: '/workflows/permit-denial-response'
      path: '/workflows/permit-denial-response'
      fullPath: '/workflows/permit-denial-response'
      preLoaderRoute: typeof WorkflowsPermitDenialResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-benefits-notice': {
      id: '/workflows/respond-to-a-benefits-notice'
      path: '/workflows/respond-to-a-benefits-notice'
      fullPath: '/workflows/respond-to-a-benefits-notice'
      preLoaderRoute: typeof WorkflowsRespondToABenefitsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-court-summons': {
      id: '/workflows/respond-to-a-court-summons'
      path: '/workflows/respond-to-a-court-summons'
      fullPath: '/workflows/respond-to-a-court-summons'
      preLoaderRoute: typeof WorkflowsRespondToACourtSummonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-dmv-notice': {
      id: '/workflows/respond-to-a-dmv-notice'
      path: '/workflows/respond-to-a-dmv-notice'
      fullPath: '/workflows/respond-to-a-dmv-notice'
      preLoaderRoute: typeof WorkflowsRespondToADmvNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-permit-correction-notice': {
      id: '/workflows/respond-to-a-permit-correction-notice'
      path: '/workflows/respond-to-a-permit-correction-notice'
      fullPath: '/workflows/respond-to-a-permit-correction-notice'
      preLoaderRoute: typeof WorkflowsRespondToAPermitCorrectionNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-tax-notice': {
      id: '/workflows/respond-to-a-tax-notice'
      path: '/workflows/respond-to-a-tax-notice'
      fullPath: '/workflows/respond-to-a-tax-notice'
      preLoaderRoute: typeof WorkflowsRespondToATaxNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-a-uscis-notice': {
      id: '/workflows/respond-to-a-uscis-notice'
      path: '/workflows/respond-to-a-uscis-notice'
      fullPath: '/workflows/respond-to-a-uscis-notice'
      preLoaderRoute: typeof WorkflowsRespondToAUscisNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-agency-action': {
      id: '/workflows/respond-to-an-agency-action'
      path: '/workflows/respond-to-an-agency-action'
      fullPath: '/workflows/respond-to-an-agency-action'
      preLoaderRoute: typeof WorkflowsRespondToAnAgencyActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-irs-notice': {
      id: '/workflows/respond-to-an-irs-notice'
      path: '/workflows/respond-to-an-irs-notice'
      fullPath: '/workflows/respond-to-an-irs-notice'
      preLoaderRoute: typeof WorkflowsRespondToAnIrsNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-an-ssa-notice': {
      id: '/workflows/respond-to-an-ssa-notice'
      path: '/workflows/respond-to-an-ssa-notice'
      fullPath: '/workflows/respond-to-an-ssa-notice'
      preLoaderRoute: typeof WorkflowsRespondToAnSsaNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-code-enforcement-notice': {
      id: '/workflows/respond-to-code-enforcement-notice'
      path: '/workflows/respond-to-code-enforcement-notice'
      fullPath: '/workflows/respond-to-code-enforcement-notice'
      preLoaderRoute: typeof WorkflowsRespondToCodeEnforcementNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-cp14-notice': {
      id: '/workflows/respond-to-cp14-notice'
      path: '/workflows/respond-to-cp14-notice'
      fullPath: '/workflows/respond-to-cp14-notice'
      preLoaderRoute: typeof WorkflowsRespondToCp14NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-cp2000-notice': {
      id: '/workflows/respond-to-cp2000-notice'
      path: '/workflows/respond-to-cp2000-notice'
      fullPath: '/workflows/respond-to-cp2000-notice'
      preLoaderRoute: typeof WorkflowsRespondToCp2000NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/ssa-notice': {
      id: '/workflows/ssa-notice'
      path: '/workflows/ssa-notice'
      fullPath: '/workflows/ssa-notice'
      preLoaderRoute: typeof WorkflowsSsaNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/tax-notice': {
      id: '/workflows/tax-notice'
      path: '/workflows/tax-notice'
      fullPath: '/workflows/tax-notice'
      preLoaderRoute: typeof WorkflowsTaxNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/tenant-eviction-response': {
      id: '/workflows/tenant-eviction-response'
      path: '/workflows/tenant-eviction-response'
      fullPath: '/workflows/tenant-eviction-response'
      preLoaderRoute: typeof WorkflowsTenantEvictionResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/tenant-repair-demand': {
      id: '/workflows/tenant-repair-demand'
      path: '/workflows/tenant-repair-demand'
      fullPath: '/workflows/tenant-repair-demand'
      preLoaderRoute: typeof WorkflowsTenantRepairDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/transunion-dispute': {
      id: '/workflows/transunion-dispute'
      path: '/workflows/transunion-dispute'
      fullPath: '/workflows/transunion-dispute'
      preLoaderRoute: typeof WorkflowsTransunionDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/uscis-notice': {
      id: '/workflows/uscis-notice'
      path: '/workflows/uscis-notice'
      fullPath: '/workflows/uscis-notice'
      preLoaderRoute: typeof WorkflowsUscisNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/health': {
      id: '/api/admin/health'
      path: '/api/admin/health'
      fullPath: '/api/admin/health'
      preLoaderRoute: typeof ApiAdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/': {
      id: '/api/cases/'
      path: '/api/cases'
      fullPath: '/api/cases/'
      preLoaderRoute: typeof ApiCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$caseId': {
      id: '/api/cases/$caseId'
      path: '/api/cases/$caseId'
      fullPath: '/api/cases/$caseId'
      preLoaderRoute: typeof ApiCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/create': {
      id: '/api/cases/create'
      path: '/api/cases/create'
      fullPath: '/api/cases/create'
      preLoaderRoute: typeof ApiCasesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MailAPdfRoute: MailAPdfRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RespondToAGovernmentNoticeRoute: RespondToAGovernmentNoticeRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  WorkflowsAgencyActionRoute: WorkflowsAgencyActionRoute,
  WorkflowsAnalyzeRoute: WorkflowsAnalyzeRoute,
  WorkflowsBenefitsNoticeRoute: WorkflowsBenefitsNoticeRoute,
  WorkflowsClaimProofPackageRoute: WorkflowsClaimProofPackageRoute,
  WorkflowsCodeEnforcementRoute: WorkflowsCodeEnforcementRoute,
  WorkflowsCourtSummonsRoute: WorkflowsCourtSummonsRoute,
  WorkflowsCp14ResponseRoute: WorkflowsCp14ResponseRoute,
  WorkflowsCp2000ResponseRoute: WorkflowsCp2000ResponseRoute,
  WorkflowsCp504ResponseRoute: WorkflowsCp504ResponseRoute,
  WorkflowsCp523ResponseRoute: WorkflowsCp523ResponseRoute,
  WorkflowsDmvNoticeRoute: WorkflowsDmvNoticeRoute,
  WorkflowsEquifaxDisputeRoute: WorkflowsEquifaxDisputeRoute,
  WorkflowsExperianDisputeRoute: WorkflowsExperianDisputeRoute,
  WorkflowsFileAppealRoute: WorkflowsFileAppealRoute,
  WorkflowsIrsNoticeRoute: WorkflowsIrsNoticeRoute,
  WorkflowsPermitCorrectionRoute: WorkflowsPermitCorrectionRoute,
  WorkflowsPermitDenialResponseRoute: WorkflowsPermitDenialResponseRoute,
  WorkflowsRespondToABenefitsNoticeRoute:
    WorkflowsRespondToABenefitsNoticeRoute,
  WorkflowsRespondToACourtSummonsRoute: WorkflowsRespondToACourtSummonsRoute,
  WorkflowsRespondToADmvNoticeRoute: WorkflowsRespondToADmvNoticeRoute,
  WorkflowsRespondToAPermitCorrectionNoticeRoute:
    WorkflowsRespondToAPermitCorrectionNoticeRoute,
  WorkflowsRespondToATaxNoticeRoute: WorkflowsRespondToATaxNoticeRoute,
  WorkflowsRespondToAUscisNoticeRoute: WorkflowsRespondToAUscisNoticeRoute,
  WorkflowsRespondToAnAgencyActionRoute: WorkflowsRespondToAnAgencyActionRoute,
  WorkflowsRespondToAnIrsNoticeRoute: WorkflowsRespondToAnIrsNoticeRoute,
  WorkflowsRespondToAnSsaNoticeRoute: WorkflowsRespondToAnSsaNoticeRoute,
  WorkflowsRespondToCodeEnforcementNoticeRoute:
    WorkflowsRespondToCodeEnforcementNoticeRoute,
  WorkflowsRespondToCp14NoticeRoute: WorkflowsRespondToCp14NoticeRoute,
  WorkflowsRespondToCp2000NoticeRoute: WorkflowsRespondToCp2000NoticeRoute,
  WorkflowsSsaNoticeRoute: WorkflowsSsaNoticeRoute,
  WorkflowsTaxNoticeRoute: WorkflowsTaxNoticeRoute,
  WorkflowsTenantEvictionResponseRoute: WorkflowsTenantEvictionResponseRoute,
  WorkflowsTenantRepairDemandRoute: WorkflowsTenantRepairDemandRoute,
  WorkflowsTransunionDisputeRoute: WorkflowsTransunionDisputeRoute,
  WorkflowsUscisNoticeRoute: WorkflowsUscisNoticeRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiAdminHealthRoute: ApiAdminHealthRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiCasesCaseIdRoute: ApiCasesCaseIdRoute,
  ApiCasesCreateRoute: ApiCasesCreateRoute,
  ApiCasesIndexRoute: ApiCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
